version: '3.3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    user: '${USER_ID}:${GROUP_ID}'
    restart: unless-stopped
    image: grafikart/php:1.0.4
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: serverName=linkmat
      APP_ENV: dev
      MAIL_DSN: sendmail://default
  db:
    restart: unless-stopped
    image: postgres:12-alpine
    ports:
      - 5432:5432 # On expose le port pour pouvoir inspecter la base pendant la phase de développement
    environment:
      POSTGRES_PASSWORD: linkmat
      POSTGRES_USER: linkmat
      POSTGRES_DB: linkmat
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./var:/var/www/var

  # Dev tools
  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
  mail:
    image: mailhog/mailhog
    ports:
      - 1080:8025
  node:
    user: '${USER_ID}:${GROUP_ID}'
    build:
      context: ./tools/docker/node
    command: yarn run dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
volumes:
  db-data:
    driver: local

networks:
  dev:
